FROM <base_image>
    
# Set the working directory
WORKDIR /app
    
# Copy the application files to the container
COPY . .
    
# Install dependencies (if any)
RUN <command_to_install_dependencies>
    
# Expose the necessary ports
EXPOSE <port_number>
    
# Define the command to run the application
CMD ["<command_to_run_application>"]